[build]
  command = "./build.sh"
  functions = "api/"
  publish = "static/"

[dev]
  command = "pip install -r requirements.txt && python app.py"
  targetPort = 5001
  publish = "static"

[[redirects]]
  from = "/*"
  to = "/api/index"
  status = 200 