[build]
  command = "bash build.sh"
  publish = "static"

[functions]
  directory = "api"

[build.environment]
  PYTHON_VERSION = "3.11"

[[redirects]]
  from = "/*"
  to = "/.netlify/functions/index"
  status = 200 