[build]
  command = "bash build.sh"
  publish = "."

[functions]
  directory = "api"

[build.environment]
  PYTHON_VERSION = "3.11"

[[redirects]]
  from = "/*"
  to = "/.netlify/functions/index"
  status = 200
  force = true
  conditions = {Role = ["!admin"]}

[[redirects]]
  from = "/static/*"
  to = "/:splat"
  status = 200 